CREATE TABLE `printer_group` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;


ALTER TABLE `printer`
	ADD COLUMN `printerGroupId` SMALLINT NOT NULL DEFAULT 0 AFTER `id`;


ALTER TABLE `discount`
	ADD COLUMN `allDiscountGroup` TINYINT NOT NULL DEFAULT 0 AFTER `discountGroupId`;

ALTER TABLE `discount`
	CHANGE COLUMN `discAmount` `discAmount` INT NOT NULL DEFAULT '0' AFTER `discRate`,
	ADD COLUMN `maxDiscount` INT NOT NULL DEFAULT '0' AFTER `discAmount`;

ALTER TABLE `discount`
	ADD COLUMN `postDiscountSC` TINYINT NOT NULL DEFAULT 0 AFTER `maxDiscount`,
	ADD COLUMN `postDiscountTax` TINYINT NOT NULL DEFAULT 0 AFTER `postDiscountSC`;

ALTER TABLE `discount`
	ADD COLUMN `remark` TINYINT(4) NOT NULL DEFAULT '0' AFTER `postDiscountTax`;
