CREATE TABLE `cashback` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(250) NOT NULL COLLATE 'utf16_bin',
	`description` TEXT(32767) NOT NULL COLLATE 'utf16_bin',
	`earningStartDate` DATE NOT NULL DEFAULT '2025-01-01',
	`earningEndDate` DATE NOT NULL DEFAULT '2025-01-01',
	`redeemStartDate` DATE NOT NULL DEFAULT '2025-01-01',
	`redeemEndDate` DATE NOT NULL DEFAULT '2025-01-01',
	`x1` TINYINT(4) NOT NULL DEFAULT '0',
	`x2` TINYINT(4) NOT NULL DEFAULT '0',
	`outletId` SMALLINT(6) NOT NULL DEFAULT '0',
	`status` TINYINT(4) NOT NULL DEFAULT '1',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=9
;


CREATE TABLE `cashback_amount` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`cashbackId` SMALLINT(6) NOT NULL DEFAULT '0',
	`earnMin` INT(11) NOT NULL DEFAULT '0',
	`earnMax` INT(11) NOT NULL DEFAULT '0',
	`cashbackMin` INT(11) NOT NULL DEFAULT '0',
	`cashbackMax` INT(11) NOT NULL DEFAULT '0',
	`redeemMinAmount` INT(11) NOT NULL DEFAULT '0',
	`status` TINYINT(4) NOT NULL DEFAULT '1',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=19
;

CREATE TABLE `cashback_outlet` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`cashbackId` SMALLINT(6) NOT NULL DEFAULT '0',
	`outletId` VARCHAR(250) NOT NULL COLLATE 'utf16_bin',
	`status` TINYINT(4) NOT NULL DEFAULT '1',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=4
;

CREATE TABLE `cashback_payment` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`cashbackId` SMALLINT(6) NOT NULL DEFAULT '0',
	`paymentId` TINYINT(4) NOT NULL DEFAULT '0',
	`status` TINYINT(4) NOT NULL DEFAULT '1',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=48
;
