CREATE TABLE `daily_schedule` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`days` TINYINT(4) NOT NULL DEFAULT '0',
	`openHour` TIME NOT NULL DEFAULT '00:00:00',
	`closeHour` TIME NOT NULL DEFAULT '00:00:00',
	`mon` SMALLINT(6) NOT NULL DEFAULT '0',
	`tue` SMALLINT(6) NOT NULL DEFAULT '0',
	`wed` SMALLINT(6) NOT NULL DEFAULT '0',
	`thu` SMALLINT(6) NOT NULL DEFAULT '0',
	`fri` SMALLINT(6) NOT NULL DEFAULT '0',
	`sat` SMALLINT(6) NOT NULL DEFAULT '0',
	`sun` SMALLINT(6) NOT NULL DEFAULT '0',
	`status` SMALLINT(6) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=5
;
