CREATE TABLE `discount` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`discountGroupId` SMALLINT(6) NOT NULL DEFAULT '0',
	`allDiscountGroup` TINYINT(4) NOT NULL DEFAULT '0',
	`allLevel` TINYINT(4) NOT NULL DEFAULT '1',
	`allOutlet` TINYINT(4) NOT NULL DEFAULT '1',
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`discRate` DECIMAL(5,2) NULL DEFAULT NULL,
	`discAmount` INT(11) NOT NULL DEFAULT '0',
	`maxDiscount` INT(11) NOT NULL DEFAULT '0',
	`requiredItemTotal` INT(11) NOT NULL DEFAULT '0',
	`postDiscountSC` TINYINT(4) NOT NULL DEFAULT '0',
	`postDiscountTax` TINYINT(4) NOT NULL DEFAULT '0',
	`remark` TINYINT(4) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`status` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=100
;

CREATE TABLE `discount_level` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`discountId` SMALLINT(6) NOT NULL DEFAULT '0',
	`employeeAuthLevelId` SMALLINT(6) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=86
;

CREATE TABLE `discount_group` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=10
;
