CREATE TABLE `check_payment_group` (
	`id` TINYINT(4) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=6
;

CREATE TABLE `check_payment_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`setDefault` TINYINT(4) NOT NULL DEFAULT '0',
	`paymentGroupId` SMALLINT(6) NOT NULL DEFAULT '0',
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`autoMatchAmount` TINYINT(4) NULL DEFAULT '1',
	`maxlimit` DECIMAL(3,2) NULL DEFAULT NULL,
	`openDrawer` TINYINT(4) NULL DEFAULT '0',
	`checkPaymentTypePopupId` SMALLINT(6) NOT NULL DEFAULT '0',
	`checkPaymentTypePopupRequirement` TINYINT(4) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=102
;

CREATE TABLE `check_payment_type_popup` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(240) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=2
;


CREATE TABLE `check_cash_type` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`value` DECIMAL(8,2) NULL DEFAULT NULL,
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=15
;
