CREATE TABLE `printer` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`printerGroupId` SMALLINT(6) NOT NULL DEFAULT '0',
	`printerTypeCon` VARCHAR(50) NOT NULL DEFAULT 'ip' COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`ipAddress` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`port` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`printerId2` TINYINT(4) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=16
;

CREATE TABLE `printer_group` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=12
;

CREATE TABLE `print_queue` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`dailyCheckId` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`cartId` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`cartItemId` INT(11) NOT NULL DEFAULT '0',
	`menuId` INT(11) NOT NULL DEFAULT '0',
	`rushPrinting` TINYINT(4) NOT NULL DEFAULT '0',
	`so` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`message` LONGTEXT NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`printerId` SMALLINT(6) NOT NULL DEFAULT '0',
	`printerId2` SMALLINT(6) NOT NULL DEFAULT '0',
	`consoleError` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`status` TINYINT(4) NOT NULL DEFAULT '0',
	`status2` TINYINT(4) NOT NULL DEFAULT '0',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT current_timestamp(),
	`inputBy` INT(11) NULL DEFAULT NULL,
	`updateDate` DATETIME NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
	`updateBy` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=41
;

CREATE TABLE `print_queue_status` (
	`id` TINYINT(4) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
