CREATE TABLE `menu_tax_sc` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`desc` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`taxRate` TINYINT(4) NOT NULL DEFAULT '0',
	`taxNote` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`taxStatus` TINYINT(4) NULL DEFAULT NULL,
	`scRate` TINYINT(4) NOT NULL DEFAULT '0',
	`scNote` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`scStatus` TINYINT(4) NULL DEFAULT NULL,
	`scTaxIncluded` TINYINT(4) NOT NULL DEFAULT '0',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=7
;


CREATE TABLE `menu_tax_sc_status` (
	`id` TINYINT(4) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
