CREATE TABLE `outlet` (
	`id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
	`posMode` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`priceNo` TINYINT(4) NOT NULL DEFAULT '1',
	`printerId` TINYINT(4) NOT NULL DEFAULT '1',
	`descs` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`tel` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`fax` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`email` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`company` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`address` TEXT NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`street` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`city` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`country` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`greeting1` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`greeting2` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`greeting3` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`greeting4` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`greeting5` VARCHAR(200) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`panel` SMALLINT(6) NOT NULL,
	`overDue` TIME NOT NULL DEFAULT '01:00:00',
	`sorting` TINYINT(4) NOT NULL DEFAULT '9',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=1005
;


CREATE TABLE `outlet_floor_plan` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`outletId` SMALLINT(6) NULL DEFAULT NULL,
	`desc1` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`image` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`sorting` TINYINT(4) NULL DEFAULT '99',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=5443
;

CREATE TABLE `outlet_table_map` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`outletId` SMALLINT(6) NULL DEFAULT NULL,
	`outletFloorPlandId` SMALLINT(6) NULL DEFAULT '1',
	`tableName` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`tableNameExt` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`desc1` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`desc2` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`desc3` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`class` TINYINT(4) NULL DEFAULT NULL,
	`seatcnt` TINYINT(4) NULL DEFAULT NULL,
	`posY` SMALLINT(6) NULL DEFAULT NULL,
	`posX` SMALLINT(6) NULL DEFAULT NULL,
	`width` SMALLINT(6) NULL DEFAULT NULL,
	`height` SMALLINT(6) NULL DEFAULT NULL,
	`capacity` TINYINT(4) NULL DEFAULT NULL,
	`shape` TINYINT(4) NULL DEFAULT NULL,
	`seatpos` TINYINT(4) NULL DEFAULT NULL,
	`seatarr` TINYINT(4) NULL DEFAULT NULL,
	`default` VARCHAR(2) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`consume` DECIMAL(3,2) NULL DEFAULT NULL,
	`icon` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`presence` TINYINT(2) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=161
;


CREATE TABLE `template_table_map` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`capacity` TINYINT(4) NOT NULL DEFAULT '4',
	`image` VARCHAR(250) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`icon` VARCHAR(250) NOT NULL DEFAULT '' COLLATE 'utf16_bin',
	`width` SMALLINT(6) NOT NULL DEFAULT '50',
	`height` SMALLINT(6) NOT NULL DEFAULT '50',
	`presence` TINYINT(4) NOT NULL DEFAULT '1',
	`inputDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`inputBy` SMALLINT(6) NOT NULL DEFAULT '1',
	`updateDate` DATETIME NOT NULL DEFAULT '2025-01-01 00:00:00',
	`updateBy` SMALLINT(6) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
